import "./globals.css";

export const metadata = {
  title: "Learning Next.js 13",
  description: "Generated by create next app",
  keywords: "learning, next.js, next.js13",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
